---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Task API"
host: "kpp6zrebs6.execute-api.us-east-1.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /DailyEmailLambda:
    x-amazon-apigateway-any-method:
      responses:
        200:
          description: "200 response"
      security:
      - sigv4: []
  /deleteTaskLambda:
    x-amazon-apigateway-any-method:
      responses:
        200:
          description: "200 response"
      security:
      - sigv4: []
  /getTasksLambda:
    x-amazon-apigateway-any-method:
      responses:
        200:
          description: "200 response"
      security:
      - sigv4: []
  /postTaskLambda:
    x-amazon-apigateway-any-method:
      responses:
        200:
          description: "200 response"
      security:
      - sigv4: []
  /putTaskLambda:
    x-amazon-apigateway-any-method:
      responses:
        200:
          description: "200 response"
      security:
      - sigv4: []
  /tasks:
    get:
      operationId: "getTasks"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Task"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    post:
      operationId: "saveTask"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Task"
        required: true
        schema:
          $ref: "#/definitions/Task"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Task"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
          schema:
            $ref: "#/definitions/Error"
    put:
      operationId: "updateTask"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Task"
        required: true
        schema:
          $ref: "#/definitions/Task"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Task"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
    delete:
      operationId: "deleteTask"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses: {}
securityDefinitions:
  sigv4:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "awsSigv4"
definitions:
  Task:
    type: "object"
    required:
    - "description"
    - "priority"
    properties:
      user:
        type: "string"
        description: "User's email address"
        title: "User"
        minLength: 5
        maxLength: 254
      description:
        type: "string"
        title: "Description of the task"
        minLength: 1
      priority:
        type: "integer"
        description: "Task priority, as a single-digit integer. 0 is highest priority"
        title: "Priority"
        minimum: 0.0
        maximum: 9.0
      completed:
        type: "string"
        format: "date-time"
        description: "Completed datetime, formatted as an ISO8601 string"
        title: "Completed"
  Error:
    type: "object"
    required:
    - "errorMessage"
    properties:
      errorMessage:
        type: "string"
